### PR TITLE
clang is supported everywhere now

### PR DESCRIPTION
**Pull request by axel-h**
This is following up on the comment https://github.com/seL4/ci-actions/pull/297#issuecomment-1881904182, we can use clang everywhere as the builds seem to work fine. So remove the blockers here, they should be put into specific workflow the in case there are still issues.

Test run is here: https://github.com/axel-h/seL4/actions/runs/7464262889/job/20310849733?pr=137 (added dummy for RV32;  removed some HW platforms so the build does not take ages)

### CODE REVIEW

**Review by lsf37 — APPROVED** [review]
Cool, looks good.

Thanks for providing the test runs. I've checked the plain base images for hifive and tx1 on the machine queue and they appear to work without problems, so I'm happy to let this loose on the bigger test runs and see if they all work.

**Comment by lsf37** [comment]
Ok, so there is one clang issue remaining after all: on TX1, the combination of SMP+HYP+MCS fails consistently with clang (and do succeed for gcc).

See e.g. https://github.com/seL4/seL4/actions/runs/7468884979/job/20367008152?pr=1156

They are getting suck (timing out) on
```
<testcase classname="sel4test" name="SCHED_CONTEXT_0014">
  Running test SCHED_CONTEXT_0014 (Test deleting a scheduling context while it runs out of budget on another core)
```

Unless you have immediate fix, I'd exclude that combination from the test for now and open an issue for it.

**Comment by axel-h** [comment]
I don't have a fix here.

**Comment by lsf37** [comment]
Ok, see #300 now. Turns out this issue already exists for the TX2 and ODROID_C4.

**Pull request merged**
