### PR TITLE
sel4test hardware runs

### PR DESCRIPTION
**Pull request by lsf37**
This action downloads previously built images and runs them on specified hardware platforms using the machine queue at UNSW.

The boards and the machine queue are still not entirely stable, but the logic is there and things mostly work.

### CODE REVIEW

**Comment by lsf37** [comment]
The bashism check fails on the usual command, which should be fine to ignore.

Longer-term this action will probably not be using ssh anyway, or if it does, will run on a separate account. Currently it is using my UNSW login for testing.

**Comment by lsf37** [comment]
There is one last thing I want to test before this is ready for review, which is reducing the time for `ControlPersist`, because I have the feeling GitHub might actually be waiting for those connections to terminate and this is what is sometimes keeping the post action from running when the job is cancelled (the GH post-action timeout seems to be 5m, and `ControlPersist` was longer). Maybe that's not it, but I'm giving it a shot.

**Comment by lsf37** [comment]
Ok, this has also worked, or at least no made anything worse, the run [here](https://github.com/lsf37/seL4/runs/3266711286) was properly cancelled and lock was free'd.

This is now ready for review.

**Review by Xaphiosis — APPROVED** [review]

**Comment by lsf37** [comment]
(rebased)

**Pull request merged**
