### PR TITLE
more verified platform variations

### PR DESCRIPTION
**Pull request by lsf37**
This introduces the `L4V_PLAT` input for aws-proofs and preprocess actions, and extends the C parser runs to include more boards/combinations.

### CODE REVIEW

**Review by mbrcknl — APPROVED** [review]
Looks fine. I guess there will be a subsequent l4v PR to make use of L4V_PLAT?

**Comment by mbrcknl** [comment]
Actually, this will require some tweaks to `l4v/spec/cspec/c/export-kernel-builds.py`, since it does its own construction of the artefact path, and doesn't actually use `L4V_ARCH_FEATURES`. My bad for writing the comment that implied that it did use `L4V_ARCH_FEATURES`.

The main reason it does its own path construction is so it can do separate builds for each optimisation level, with the optimisation level also included in the directory name.

I'll send a quick l4v PR to update the export script. And if you don't mind, I'll push an extra commit onto your branch here to improve that comment.

**Comment by lsf37** [comment]
> Looks fine. I guess there will be a subsequent l4v PR to make use of L4V_PLAT?

Yes, was aiming for today, but lots of distractions currently

**Comment by lsf37** [comment]
>  And if you don't mind, I'll push an extra commit onto your branch here to improve that comment.

No problem, looks good from here. (But you you please add the sign-off line? :-))

**Comment by lsf37** [comment]
Corresponding PR now in https://github.com/seL4/l4v/pull/639

**Comment by mbrcknl** [comment]
> No problem, looks good from here. (But could you please add the sign-off line? :-))

Done. Sorry about that!

**Comment by lsf37** [comment]
> > No problem, looks good from here. (But could you please add the sign-off line? :-))
> 
> Done. Sorry about that!

No worries!

**Pull request merged**
