### PR TITLE
Sim scripts: Fix issue 340

### PR DESCRIPTION
**Pull request by wom-bat**
Add success criteria for each simulation run.  Otherwise the string is empty and never matches.

### CODE REVIEW

**Comment by axel-h** [comment]
see 
- https://github.com/seL4/ci-actions/issues/339 
- https://github.com/seL4/ci-actions/pull/340

**Comment by lsf37** [comment]
That can't be the reason for sel4test, where it is provided, but still failing.

**Comment by lsf37** [comment]
Still need to confirm with a debug run, but the success string is provided [here](https://github.com/seL4/ci-actions/blob/49c59bf2b22ff88fecf7ba8da61404bbef6d620a/camkes-vm/builds.yml#L7-L9) as default:

```yml
default:
  success: 'buildroot login:'
  error: 'Halting...'
```

(which reminds me that we should also match for the failure case and terminate early there instead of timing out -- Bamboo didn't do that, which is why it's not in the current scripts, but it should be easy to add once we've figured out what is going on)

**Comment by lsf37** [comment]
Closing this one, since it's not changing behaviour on the test.

**Pull request closed without merging**
