### PR TITLE
support LLVM for RISCV64 kernel stand alone build

### PR DESCRIPTION
**Pull request by axel-h**
See https://github.com/seL4/seL4/pull/1154 for a test run

### CODE REVIEW

**Review by lsf37 — APPROVED** [review]
Looking good. And I see the test worked as well. Nice.

We had previously excluded clang for RISCV, because there were some problems. Have these been fixed or is it just that more recent compiler versions now work?

**Comment by axel-h** [comment]
No sure if somebody was actively tracking this. LLVM has been working for me for some time now.

**Comment by lsf37** [comment]
Cool, we should try switching on clang for more of the RISCV tests then.

**Comment by axel-h** [comment]
What I'm still not sure about is what clang triple we prefer and why we do this: `riscv64-unknown-elf` or `riscv64-linux-gnu`

**Comment by lsf37** [comment]
For the pure compilation check I don't think it actually matters for the kernel, because we're not linking with any libraries anyway. I guess that makes the more "honest" one `riscv64-unknown-elf`

**Comment by axel-h** [comment]
True. Wwe no longer have `riscv64-linux-gnu` anyway. I was just fooled again by some other scripts that still contain this, but it is completely unused and thus there was never an issues. More PRs to come...

**Pull request merged**
