### PR TITLE
camkes-vm: add vm_introspect

### PR DESCRIPTION
**Pull request by axel-h**
Addresses https://github.com/seL4/camkes-vm-examples/issues/38

### CODE REVIEW

**Comment by axel-h** [comment]
Seem I can't test this in github CI, see https://github.com/seL4/ci-actions/issues/267

**Comment by lsf37** [comment]
Will have a look if I can write up how I test changes like this. It's not a short process, but I don't think there are any shortcuts there.

**Comment by axel-h** [comment]
This works, but it shows that the vm_introspect build is broken, So we can't merge this until that is fixed, see https://github.com/seL4/camkes-vm-examples/issues/38

**Comment by axel-h** [comment]
https://github.com/seL4/camkes-vm-examples/pull/39 fixed the build breaker and it seem to work again then in the simulation.

**Review by lsf37 — APPROVED** [review]
:+1: Good to merge once the vm-examples fix is in.

**Pull request merged**
